print('Enter the name of cat 1:')
cateName1 = input()
print('Enter the name of cat 2:')
cateName2 = input()
print('Enter the name of cat 3:')
cateName3 = input()
print('Enter the name of cat 4:')
cateName4 = input()
print('Enter the name of cat 5:')
cateName5 = input()
print('Enter the name of cat 6:')
cateName5 = input()
print('The cat names are:')
print(catName1 + '' + catName2 + '' + catName3 + catName4 + '' + catName5 + catName6)
